version: '2'
services:
    frontend:
            build: ./frontend
            links:
                - backend
            ports:
                - "4200:4200"
                - "49153:49153"
            expose:
                - "4200"
                - "49153"
            volumes:
                - ./frontend:/usr/src/app
    backend:
        build: ./api/
        volumes:
            - ./api/:/var/www/html/
        links:
            - db
        environment:
            ENABLE_ENV_FILE: 1
            ENABLE_LOCALCONF: 1
        ports:
            - "4201:80"
        expose:
            - "4201"
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret-root
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
